services:
  web:
    container_name: paritet_django
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 2 --timeout 300
      "
    volumes:
      - static:/backend/static
      - media:/backend/media
      - ./backend/gallery/migrations:/backend/gallery/migrations
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8000

  db:
    container_name: paritet_db
    image: postgres:16.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  frontend:
    container_name: paritet_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_TOKEN: ${API_TOKEN}
    ports:
      - "80:80"
    volumes:
      - static:/backend/static
      - media:/backend/media
    

    

volumes:
  postgres_data:
  static:
  media:
